services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - resourcespace-db
    volumes:
      - /mnt/large_storage/resourcespace:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
    networks:
      - resourcespace-net
    expose:
      - "80"
    environment:
      - RS_DB_HOST=resourcespace-db
      - RS_DB_NAME=${MYSQL_DATABASE}
      - RS_DB_USER=${MYSQL_USER}
      - RS_DB_PASSWORD=${MYSQL_PASSWORD}

  resourcespace-db:
    image: mariadb:10.11
    container_name: resourcespace-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - resourcespace_db_data:/var/lib/mysql
    networks:
      - resourcespace-net

networks:
  resourcespace-net:

volumes:
  resourcespace_db_data:
